import { PlaceType, Spot } from "@/types/spot";

export const locations: Spot[] = [
  {
    id: "1",
    rating: 4.5,
    photos: [],
    googleMapsUri: "https://maps.app.goo.gl/1234567890",
    location: { latitude: -2.976, longitude: 104.775 },
    types: ["restaurant"] as PlaceType[],
    formattedAddress: "Palembang, Indonesia",
    displayName: { text: "Local Restaurant", languageCode: "en" },
  },
  {
    id: "2",
    rating: 4.5,
    photos: [],
    googleMapsUri: "https://maps.app.goo.gl/1234567890",
    location: { latitude: -2.983, longitude: 104.783 },
    types: ["cafe"] as PlaceType[],
    formattedAddress: "Cafe Example, Palembang, Indonesia",
    displayName: { text: "Coffee Shop", languageCode: "en" },
  },
  {
    id: "3",
    rating: 4.5,
    photos: [],
    googleMapsUri: "https://maps.app.goo.gl/1234567890",
    location: { latitude: -2.97, longitude: 104.77 },
    types: ["museum"] as PlaceType[],
    formattedAddress: "Museum Example, Palembang, Indonesia",
    displayName: { text: "History Museum", languageCode: "en" },
  },
  {
    id: "4",
    rating: 4.5,
    photos: [],
    googleMapsUri: "https://maps.app.goo.gl/1234567890",
    location: { latitude: -2.98, longitude: 104.76 },
    types: ["park"] as PlaceType[],
    formattedAddress: "Park Example, Palembang, Indonesia",
    displayName: { text: "City Park", languageCode: "en" },
  },
  {
    id: "5",
    rating: 4.2,
    photos: [],
    googleMapsUri: "https://maps.app.goo.gl/1234567890",
    location: { latitude: -2.985, longitude: 104.78 },
    types: ["hospital"] as PlaceType[],
    formattedAddress: "Hospital Example, Palembang, Indonesia",
    displayName: { text: "General Hospital", languageCode: "en" },
  },
  {
    id: "6",
    rating: 4.8,
    photos: [],
    googleMapsUri: "https://maps.app.goo.gl/1234567890",
    location: { latitude: -2.975, longitude: 104.785 },
    types: ["shopping_mall"] as PlaceType[],
    formattedAddress: "Mall Example, Palembang, Indonesia",
    displayName: { text: "Shopping Center", languageCode: "en" },
  },
];
